version: "3"
services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: bengak-uas-awan
        container_name: uas-awan-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html/
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: uas-awan-webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html/
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql:latest
        container_name: uas-awan-db
        # restart: unless-stopped
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: uas_awan
            MYSQL_PASSWORD: root

        ports:
            - "3306:3306"

        # volumes:
        #     - ./mysql/data:/var/lib/mysql
        #     - ./mysql/conf.d:/etc/mysql/conf.d

        volumes:
            # - ./docker/mariadb/config:/etc/mysql/conf.d:ro
            - ./db/data:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d

        networks:
            - app-network

networks:
    app-network:
        driver: bridge
