name: PHP Composer

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Konek SSH
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd uas-awan/
                      git pull
    push_to_registry:
        name: Push Docker Images
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ Secrets.DOCKER_USERNAME }}
                  password: ${{ Secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker Images
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: ${{ Secrets.DOCKER_USERNAME }}/uas-awan:latest

    deploy_images:
        name: Setup SSH and deploy images
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Docker compose with Load Balancer
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd uas-awan/
                      sudo docker-compose up -d
